listener 1883
protocol mqtt
allow_anonymous true
max_packet_size 65536
max_queued_messages 100000
log_dest stdout
log_type error
log_type warning
log_type notice
log_type subscribe
log_type unsubscribe
log_timestamp true
persistence true
persistence_location /mosquitto/data/
plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/dynsec/dynamic-security.json
